Fix

diff --git a/.github/workflows/thirteenth_workflow.yml b/.github/workflows/thirteenth_workflow.yml
--- a/.github/workflows/thirteenth_workflow.yml
+++ b/.github/workflows/thirteenth_workflow.yml
@@ -6,6 +6,9 @@ jobs:
     job:
         runs-on: ubuntu-latest
         steps:
+            - name: Failure Step
+              id: error-step
+              run: exit 1
             - name: Runs on Canceled
               if: ${{ cancelled() }}
               run: echo "Runs on Canceled"
@@ -15,8 +18,8 @@ jobs:
             - name: Runs on Success
               if: ${{ success() }}
               run: echo "Runs on Success"
-            - name: Runs on Failure
-              if: ${{ failure() }}
+            - name: Runs on Failure 
+              if: ${{ failure() && steps.error-step.conclusion == 'failure' }}
               run: echo "Runs on Failure"
     second-job:
         runs-on: ubuntu-latest
